### ISSUE TITLE
List this in react-native-sensors

### ISSUE THREAD

**Issue by DanielMSchmidt** [Noitidart/FlyThru#1]
Hey there,

It seems like you did a pretty cool project here with react-native-sensors. Would you mind if I added it to the list of projects on react-native-sensors website / readme? If you have a cool screenshot that would be extra awesome!

**Comment by Noitidart** [comment]
Thanks!!! That would be really awesome. I really appreciate you asking!  Here is a screenshot: https://i.imgur.com/FqAOH8l.png

**Comment by Noitidart** [comment]
I see you just added it, thank you!
